"""
Generate both LaTeX tables and readable CSV files for all 6 tables from parsed CSV results.
This script reads the CSV files generated by parse_all_experiments.py and creates
properly formatted LaTeX tables AND readable CSV files matching the paper format.

Usage:
    python scripts/generate_all_tables.py --results_dir <results_dir>
"""
import argparse
import csv
from pathlib import Path
import math
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument('--results_dir', required=True, help='directory containing CSV results')
args = parser.parse_args()

results_dir = Path(args.results_dir)

def fmt_with_std(mean, std, bold_if_best=False):
    """Format mean ± std, with optional bold formatting"""
    if math.isnan(mean) or math.isnan(std):
        return '-'
    
    if std == 0:
        result = f'{mean:.2f}'
    else:
        result = f'{mean:.2f}±{std:.2f}'
    
    if bold_if_best:
        result = f'\\textbf{{{result}}}'
    
    return result

def fmt_simple(val):
    """Format a simple value"""
    try:
        v = float(val)
        if math.isnan(v):
            return '-'
        return f'{v:.2f}'
    except:
        return '-'

def fmt_csv(val):
    """Format value for CSV (simple number or empty)"""
    try:
        v = float(val)
        if math.isnan(v):
            return ''
        return f'{v:.2f}'
    except:
        return ''

def fmt_csv_with_std(mean, std):
    """Format mean ± std for CSV"""
    try:
        m = float(mean)
        s = float(std)
        if math.isnan(m) or math.isnan(s):
            return ''
        if s == 0:
            return f'{m:.2f}'
        return f'{m:.2f}±{s:.2f}'
    except:
        return ''

def fmt_gain(ttc_val, clip_val):
    """Format gain (TTC - CLIP) with color coding"""
    try:
        gain = float(ttc_val) - float(clip_val)
        if math.isnan(gain):
            return '-'
        
        # Color coding: red if positive, blue if negative
        if gain > 0:
            return f'\\textcolor{{red}}{{+{gain:.2f}}}'
        else:
            return f'\\textcolor{{blue}}{{{gain:.2f}}}'
    except:
        return '-'

def read_csv_results(csv_path):
    """Read CSV results into a dictionary"""
    results = {}
    if not csv_path.exists():
        return results
    
    with csv_path.open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            dataset = row['dataset']
            if dataset not in results:
                results[dataset] = {}
            
            if 'method' in row:
                # Standard format
                method = row['method']
                results[dataset][method] = row
            else:
                # Hyperparameter format
                tau = row['tau_thres']
                beta = row['beta']
                key = f'tau{tau}_beta{beta}'
                results[dataset][key] = row
    
    return results

# Generate Table 1: PGD eps=1/255
print("Generating Table 1...")
table1_results = read_csv_results(results_dir / 'table1_pgd_eps1_results.csv')

with (results_dir / 'table1.tex').open('w', encoding='utf-8') as f:
    f.write('% Table 1: Classification accuracy on PGD eps=1/255\n')
    f.write('\\begin{tabular}{lccccccccc}\n')
    f.write('\\hline\n')
    f.write('Dataset & CLIP & CLIP-FT & TeCoA & PMG-AFT & FARE & RN & TTE & Anti-adv & TTC (ours) \\\\n+')
    f.write('\\hline\n')

    for dataset in sorted(table1_results.keys()):
        data = table1_results[dataset]

        # Extract method results
        clip = data.get('baseline', {})
        fare = data.get('fare', {})
        tecoa = data.get('tecoa', {})
        pmg = data.get('pmg_aft', {})

        # Robustness row
        f.write(f"{dataset} (Rob.) & ")
        f.write(f"{fmt_with_std(float(clip.get('adv_acc_mean', 'nan')), float(clip.get('adv_acc_std', 'nan')))} & ")
        f.write("- & ")  # CLIP-FT placeholder
        f.write(f"{fmt_with_std(float(tecoa.get('adv_acc_mean', 'nan')), float(tecoa.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(pmg.get('adv_acc_mean', 'nan')), float(pmg.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('adv_acc_mean', 'nan')), float(fare.get('adv_acc_std', 'nan')))} & ")
        f.write("- & - & - & ")  # RN, TTE, Anti-adv placeholders
        f.write(f"{fmt_with_std(float(clip.get('adv_ttc_acc_mean', 'nan')), float(clip.get('adv_ttc_acc_std', 'nan')))} \\\\n+")

        # Accuracy row
        f.write(f"{dataset} (Acc.) & ")
        f.write(f"{fmt_with_std(float(clip.get('clean_acc_mean', 'nan')), float(clip.get('clean_acc_std', 'nan')))} & ")
        f.write("- & ")  # CLIP-FT placeholder
        f.write(f"{fmt_with_std(float(tecoa.get('clean_acc_mean', 'nan')), float(tecoa.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(pmg.get('clean_acc_mean', 'nan')), float(pmg.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('clean_acc_mean', 'nan')), float(fare.get('clean_acc_std', 'nan')))} & ")
        f.write("- & - & - & ")  # RN, TTE, Anti-adv placeholders
        f.write(f"{fmt_with_std(float(clip.get('clean_ttc_acc_mean', 'nan')), float(clip.get('clean_ttc_acc_std', 'nan')))} \\\\n+")
        f.write('\\hline\n')

    f.write('\\end{tabular}\n')

# Generate Table 2: PGD eps=4/255
print("Table 2 generation removed per user request: skipping PGD eps=4/255 LaTeX generation.")

# Generate Table 3: TTC on AFT models
print("Generating Table 3...")
table3_results = read_csv_results(results_dir / 'table3_ttc_on_aft_results.csv')

with (results_dir / 'table3.tex').open('w', encoding='utf-8') as f:
    f.write('% Table 3: TTC employed on adversarially finetuned models\n')
    f.write('\\begin{tabular}{lcccc}\n')
    f.write('\\hline\n')
    f.write('Dataset & TeCoA & TeCoA+TTC & FARE & FARE+TTC \\\\\n')
    f.write('\\hline\n')
    
    for dataset in sorted(table3_results.keys()):
        data = table3_results[dataset]
        
        tecoa = data.get('tecoa', {})
        fare = data.get('fare', {})
        
        f.write(f"{dataset} & ")
        f.write(f"{fmt_with_std(float(tecoa.get('adv_acc_mean', 'nan')), float(tecoa.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(tecoa.get('adv_ttc_acc_mean', 'nan')), float(tecoa.get('adv_ttc_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('adv_acc_mean', 'nan')), float(fare.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('adv_ttc_acc_mean', 'nan')), float(fare.get('adv_ttc_acc_std', 'nan')))} \\\\\n")
    
    f.write('\\hline\n')
    f.write('\\end{tabular}\n')

# Generate Table 4: CW attack
print("Generating Table 4...")
table4_results = read_csv_results(results_dir / 'table4_cw_eps1_results.csv')

with (results_dir / 'table4.tex').open('w', encoding='utf-8') as f:
    f.write('% Table 4: Classification accuracy on CW attack eps=1/255\n')
    f.write('\\begin{tabular}{lccccccccc}\n')
    f.write('\\hline\n')
    f.write('Dataset & CLIP & CLIP-FT & TeCoA & PMG-AFT & FARE & RN & TTE & Anti-adv & TTC (ours) \\\\\n')
    f.write('\\hline\n')
    
    for dataset in sorted(table4_results.keys()):
        data = table4_results[dataset]
        
        clip = data.get('baseline', {})
        fare = data.get('fare', {})
        tecoa = data.get('tecoa', {})
        pmg = data.get('pmg_aft', {})
        
        # Similar format to Table 1
        # Robustness row
        f.write(f"{dataset} (Rob.) & ")
        f.write(f"{fmt_with_std(float(clip.get('adv_acc_mean', 'nan')), float(clip.get('adv_acc_std', 'nan')))} & ")
        f.write("- & ")
        f.write(f"{fmt_with_std(float(tecoa.get('adv_acc_mean', 'nan')), float(tecoa.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(pmg.get('adv_acc_mean', 'nan')), float(pmg.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('adv_acc_mean', 'nan')), float(fare.get('adv_acc_std', 'nan')))} & ")
        f.write("- & - & - & ")
        f.write(f"{fmt_with_std(float(clip.get('adv_ttc_acc_mean', 'nan')), float(clip.get('adv_ttc_acc_std', 'nan')))} \\\\\n")
        
        # Accuracy row
        f.write(f"{dataset} (Acc.) & ")
        f.write(f"{fmt_with_std(float(clip.get('clean_acc_mean', 'nan')), float(clip.get('clean_acc_std', 'nan')))} & ")
        f.write("- & ")
        f.write(f"{fmt_with_std(float(tecoa.get('clean_acc_mean', 'nan')), float(tecoa.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(pmg.get('clean_acc_mean', 'nan')), float(pmg.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('clean_acc_mean', 'nan')), float(fare.get('clean_acc_std', 'nan')))} & ")
        f.write("- & - & - & ")
        f.write(f"{fmt_with_std(float(clip.get('clean_ttc_acc_mean', 'nan')), float(clip.get('clean_ttc_acc_std', 'nan')))} \\\\\n")
        f.write('\\hline\n')
    
    f.write('\\end{tabular}\n')

# Generate Table 5: PGD eps=4/255 with AFT superscripts (same as Table 2)
print("Generating Table 5...")
table5_results = read_csv_results(results_dir / 'table5_pgd_eps4_aft_results.csv')

with (results_dir / 'table5.tex').open('w', encoding='utf-8') as f:
    f.write('% Table 5: Classification accuracy on PGD eps=4/255 with AFT superscripts\n')
    # Match CSV: remove per-method TTC variants for Table 5 and include TTC (CLIP) + delta
    f.write('\\begin{tabular}{lcccccc}\n')
    f.write('\\hline\n')
    f.write('Dataset & CLIP & TeCoA & FARE & PMG-AFT & TTC (ours) & Δ \\\\n+')
    f.write('\\hline\n')

    for dataset in sorted(table5_results.keys()):
        data = table5_results[dataset]

        clip = data.get('baseline', {})
        fare = data.get('fare', {})
        tecoa = data.get('tecoa', {})
        pmg = data.get('pmg_aft', {})

        # Same format as Table 2
        clip_rob = float(clip.get('adv_acc_mean', 'nan'))
        ttc_rob = float(clip.get('adv_ttc_acc_mean', 'nan'))

        # Robustness row
        f.write(f"{dataset} (Rob.) & ")
        f.write(f"{fmt_simple(clip_rob)} & ")
        f.write(f"{fmt_with_std(float(tecoa.get('adv_acc_mean', 'nan')), float(tecoa.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('adv_acc_mean', 'nan')), float(fare.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(pmg.get('adv_acc_mean', 'nan')), float(pmg.get('adv_acc_std', 'nan')))} & ")
        f.write(f"{fmt_simple(ttc_rob)} & ")
        f.write(f"{fmt_gain(ttc_rob, clip_rob)} \\\\n+")

        # Accuracy row
        clip_acc = float(clip.get('clean_acc_mean', 'nan'))
        ttc_acc = float(clip.get('clean_ttc_acc_mean', 'nan'))
        f.write(f"{dataset} (Acc.) & ")
        f.write(f"{fmt_simple(clip_acc)} & ")
        f.write(f"{fmt_with_std(float(tecoa.get('clean_acc_mean', 'nan')), float(tecoa.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(fare.get('clean_acc_mean', 'nan')), float(fare.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_with_std(float(pmg.get('clean_acc_mean', 'nan')), float(pmg.get('clean_acc_std', 'nan')))} & ")
        f.write(f"{fmt_simple(ttc_acc)} & ")
        f.write(f"{fmt_gain(ttc_acc, clip_acc)} \\\\n+")
        f.write('\\hline\n')

    f.write('\\end{tabular}\n')

# Generate Table 6: Hyperparameter study
print("Generating Table 6...")
table6_results = read_csv_results(results_dir / 'table6_hyperparam_results.csv')

with (results_dir / 'table6.tex').open('w', encoding='utf-8') as f:
    f.write('% Table 6: Effects of hyperparameters tau_thres and beta\n')
    f.write('\\begin{tabular}{ccccc}\n')
    f.write('\\hline\n')
    f.write('$\\tau_{thres}$ & $\\beta$ & Clean Acc. & Rob. Acc. & TTC Rob. Acc. \\\\\n')
    f.write('\\hline\n')
    
    for dataset in sorted(table6_results.keys()):
        data = table6_results[dataset]
        
        # Sort by tau_thres, then beta
        sorted_params = sorted(data.keys(), key=lambda x: (float(x.split('_')[0].replace('tau', '')), float(x.split('_')[1].replace('beta', ''))))
        
        for param_key in sorted_params:
            param_data = data[param_key]
            tau_val = param_key.split('_')[0].replace('tau', '')
            beta_val = param_key.split('_')[1].replace('beta', '')
            
            f.write(f"{tau_val} & {beta_val} & ")
            f.write(f"{fmt_simple(param_data.get('clean_acc_mean', 'nan'))} & ")
            f.write(f"{fmt_simple(param_data.get('adv_acc_mean', 'nan'))} & ")
            f.write(f"{fmt_simple(param_data.get('adv_ttc_acc_mean', 'nan'))} \\\\\n")
        
        break  # Only show for first dataset
    
    f.write('\\hline\n')
    f.write('\\end{tabular}\n')

print("All tables generated!")
print(f"LaTeX files saved in: {results_dir}")
print("Files generated:")
for i in range(1, 7):
    print(f"  - table{i}.tex")